name: jmq_app
description: "JMQ Service Manual — offline diagnostic tool"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_pdfview: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/db/jmq_service_manual_v4.db
    - assets/pdf/01_Engine/HFC4GB2.4D/
    - assets/pdf/01_Engine/HFC4GB2.4E/
    - assets/pdf/02_Transmission/CVT_Punch/
    - assets/pdf/02_Transmission/MF622D35/
    - assets/pdf/03_Chassis/
    - assets/pdf/04_Body/01_Structure/
    - assets/pdf/04_Body/02_Electrical/
    - assets/pdf/05_Electrical_Systems/01_Circuit_Diagrams/
    - assets/pdf/05_Electrical_Systems/02_AVM/
    - assets/pdf/05_Electrical_Systems/03_TPMS/
    - assets/pdf/06_Calibration/
    - assets/pdf/99_Firmware_Updates/MP5/
